# Generated by Django 5.1.4 on 2026-02-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('produits', '0001_initial'),
        ('societe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntreeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entree', models.CharField(choices=[('EN', 'EN – Entrée Normale'), ('ER', 'ER – Entrée Retour'), ('EI', 'EI – Entrée Inventaire'), ('EAJ', 'EAJ – Entrée Ajustement'), ('ET', 'ET – Entrée Transfert'), ('EA', 'EA – Entrée Autres')], max_length=5, verbose_name="Type d'entrée")),
                ('numero_ref', models.CharField(blank=True, max_length=50, verbose_name='N° Réquisition / Réf. fiche')),
                ('date_entree', models.DateField(verbose_name="Date d'entrée")),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('prix_revient', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de revient')),
                ('prix_vente_actuel', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de vente actuel')),
                ('statut_obr', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé OBR'), ('ECHEC', 'Échec envoi'), ('NON_CONCERNE', 'Non concerné')], default='EN_ATTENTE', max_length=20, verbose_name='Statut OBR')),
                ('message_obr', models.TextField(blank=True, verbose_name='Message OBR')),
                ('date_envoi_obr', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_stock', to='fournisseurs.fournisseur', verbose_name='Fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrees_stock', to='produits.produit', verbose_name='Produit')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees_stock', to='societe.societe')),
            ],
            options={
                'verbose_name': 'Entrée stock',
                'verbose_name_plural': 'Entrées stock',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SortieStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sortie', models.CharField(choices=[('SP', 'SP – Sortie Perte'), ('SV', 'SV – Sortie Vol'), ('SD', 'SD – Sortie Désuétude'), ('SC', 'SC – Sortie Casse'), ('SAJ', 'SAJ – Sortie Ajustement'), ('ST', 'ST – Sortie Transfert'), ('SAU', 'SAU – Sortie Autres')], max_length=5, verbose_name='Type de sortie')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Code sortie')),
                ('date_sortie', models.DateField(verbose_name='Date de sortie')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité sortie')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire / Explication')),
                ('statut_obr', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé OBR'), ('ECHEC', 'Échec envoi'), ('NON_CONCERNE', 'Non concerné')], default='EN_ATTENTE', max_length=20, verbose_name='Statut OBR')),
                ('message_obr', models.TextField(blank=True, verbose_name='Message OBR')),
                ('date_envoi_obr', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('entree_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorties', to='stock.entreestock', verbose_name='Produit (depuis stock)')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorties_stock', to='societe.societe')),
            ],
            options={
                'verbose_name': 'Sortie stock',
                'verbose_name_plural': 'Sorties stock',
                'ordering': ['-date_creation'],
            },
        ),
    ]
