# Generated by Django 6.0.3 on 2026-04-04 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0008_alter_facture_unique_together_alter_facture_numero_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreestock',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='entreestock',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_stock', to='facturer.facture', verbose_name='Facture liée'),
        ),
    ]
