# Generated by Django 6.0.3 on 2026-04-04 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0008_alter_facture_unique_together_alter_facture_numero_and_more'),
        ('stock', '0002_entreestock_commentaire_entreestock_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortiestock',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_stock', to='facturer.facture', verbose_name='Facture liée'),
        ),
    ]
