# Generated by Django 6.0.3 on 2026-04-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0008_alter_facture_unique_together_alter_facture_numero_and_more'),
        ('fournisseurs', '0001_initial'),
        ('produits', '0004_alter_produit_origine'),
        ('societe', '0008_societe_assujeti_pfl_alter_societe_assujeti_tc_and_more'),
        ('stock', '0003_sortiestock_facture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entreestock',
            unique_together={('societe', 'produit', 'facture', 'type_entree')},
        ),
        migrations.AddIndex(
            model_name='entreestock',
            index=models.Index(fields=['societe', 'produit', 'date_entree'], name='stock_entre_societe_08813f_idx'),
        ),
        migrations.AddIndex(
            model_name='entreestock',
            index=models.Index(fields=['statut_obr'], name='stock_entre_statut__470095_idx'),
        ),
        migrations.AddIndex(
            model_name='entreestock',
            index=models.Index(fields=['facture'], name='stock_entre_facture_04ce08_idx'),
        ),
    ]
