# Generated by Django 6.0.3 on 2026-05-06 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0012_alter_lignefacture_taux_tva_and_more'),
        ('fournisseurs', '0001_initial'),
        ('stock', '0004_alter_entreestock_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreestock',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_stock', to='fournisseurs.fournisseur'),
        ),
        migrations.AlterField(
            model_name='entreestock',
            name='message_obr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entreestock',
            name='numero_ref',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Référence'),
        ),
        migrations.AlterField(
            model_name='entreestock',
            name='prix_revient',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Prix de revient'),
        ),
        migrations.AlterField(
            model_name='entreestock',
            name='prix_vente_actuel',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Prix de vente actuel (TVAC)'),
        ),
        migrations.AlterField(
            model_name='entreestock',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='entreestock',
            name='statut_obr',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé OBR'), ('ECHEC', 'Échec envoi'), ('NON_CONCERNE', 'Non concerné')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='sortiestock',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='sortiestock',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_stock', to='facturer.facture'),
        ),
        migrations.AlterField(
            model_name='sortiestock',
            name='message_obr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sortiestock',
            name='prix',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Prix unitaire (TVAC)'),
        ),
        migrations.AlterField(
            model_name='sortiestock',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité sortie'),
        ),
        migrations.AlterField(
            model_name='sortiestock',
            name='statut_obr',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé OBR'), ('ECHEC', 'Échec envoi'), ('NON_CONCERNE', 'Non concerné')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='sortiestock',
            name='type_sortie',
            field=models.CharField(choices=[('SN', 'SN – Sortie Normale (Vente)'), ('SP', 'SP – Sortie Perte'), ('SV', 'SV – Sortie Vol'), ('SD', 'SD – Sortie Désuétude'), ('SC', 'SC – Sortie Casse'), ('SAJ', 'SAJ – Sortie Ajustement'), ('ST', 'ST – Sortie Transfert'), ('SAU', 'SAU – Sortie Autres')], max_length=5, verbose_name='Type de sortie'),
        ),
    ]
