# Generated by Django 6.0.3 on 2026-05-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_entreestock_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortiestock',
            name='devise',
            field=models.CharField(choices=[('BIF', 'BIF — Franc Burundais'), ('USD', 'USD — Dollar Américain'), ('EUR', 'EUR — Euro')], default='BIF', max_length=10, verbose_name='Devise'),
        ),
    ]
