# Generated by Django 6.0.3 on 2026-05-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_sortiestock_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreestock',
            name='devise',
            field=models.CharField(choices=[('BIF', 'BIF — Franc Burundais'), ('USD', 'USD — Dollar Américain'), ('EUR', 'EUR — Euro')], default='BIF', max_length=10, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='entreestock',
            name='quantite',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='sortiestock',
            name='quantite',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité sortie'),
        ),
    ]
