# Generated by Django 6.0.6 on 2026-07-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_entreestock_devise_alter_entreestock_quantite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreestock',
            name='obr_mode_envoye',
            field=models.BooleanField(default=False, editable=False, verbose_name='Mode PRODUCTION'),
        ),
        migrations.AddField(
            model_name='sortiestock',
            name='obr_mode_envoye',
            field=models.BooleanField(default=False, editable=False, verbose_name='Mode PRODUCTION'),
        ),
    ]
