# Generated by Django 6.0.6 on 2026-07-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0022_alter_facture_unique_together'),
        ('produits', '0012_alter_produit_unique_together'),
        ('societe', '0016_alter_societe_obr_base_url'),
        ('stock', '0008_entreestock_obr_mode_envoye_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entreestock',
            unique_together={('societe', 'produit', 'facture', 'type_entree', 'obr_mode_envoye')},
        ),
    ]
