# Generated by Django 6.0.3 on 2026-05-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='prix_vente',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Prix de vente HT'),
        ),
        migrations.AlterField(
            model_name='service',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=10),
        ),
    ]
