# Generated by Django 6.0.3 on 2026-05-06 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_prix_vente_alter_service_statut'),
        ('taux', '0002_alter_taux_unique_together_remove_taux_societe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='taux_tva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='taux.tauxtva', verbose_name='Taux TVA'),
        ),
    ]
