# Generated by Django 6.0.6 on 2026-07-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_taux_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='obr_mode_envoye',
            field=models.BooleanField(default=False, editable=False, verbose_name='Mode PRODUCTION'),
        ),
    ]
