# Generated by Django 5.1.4 on 2026-02-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('societe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Type de client')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_clients', to='societe.societe', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Type de client',
                'verbose_name_plural': 'Types de clients',
                'ordering': ['nom'],
                'unique_together': {('societe', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du client')),
                ('nif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF')),
                ('assujeti_tva', models.BooleanField(default=False, verbose_name='Assujetti TVA')),
                ('adresse', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse / Résidence')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='societe.societe', verbose_name='Société')),
                ('type_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.typeclient', verbose_name='Type de client')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
    ]
