# Generated by Django 5.1.4 on 2026-03-13 18:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('societe', '0005_societe_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avenue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_verification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification OBR'),
        ),
        migrations.AddField(
            model_name='client',
            name='nom_obr_officiel',
            field=models.CharField(blank=True, help_text='Nom retourné par checkTIN (ne pas modifier manuellement)', max_length=150, null=True, verbose_name='Nom officiel OBR'),
        ),
        migrations.AddField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='client',
            name='verifie_obr',
            field=models.BooleanField(default=False, verbose_name='Vérifié par OBR'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse complète'),
        ),
        migrations.AlterField(
            model_name='client',
            name='assujeti_tva',
            field=models.BooleanField(default=False, help_text='Cochez si le client paie la TVA (vat_customer_payer = 1)', verbose_name='Assujetti à la TVA'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nif',
            field=models.CharField(blank=True, help_text="Numéro d'Identification Fiscale (vérifiable via OBR)", max_length=50, null=True, verbose_name='NIF'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('societe', 'nif'), ('societe', 'nom')},
        ),
    ]
