# Generated by Django 6.0.3 on 2026-03-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_avenue_client_commune_client_cree_par_and_more'),
        ('societe', '0007_societe_email_societe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('societe', 'nif')},
        ),
        migrations.AddField(
            model_name='client',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='client',
            name='assujeti_tva',
            field=models.BooleanField(default=False, help_text="Correspond à vat_customer_payer dans l'API OBR", verbose_name='Assujetti à la TVA'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nif',
            field=models.CharField(blank=True, help_text="Numéro d'Identification Fiscale (vérifiable via checkTIN)", max_length=50, null=True, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=150, verbose_name='Nom / Raison sociale du client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom_obr_officiel',
            field=models.CharField(blank=True, help_text='Ne pas modifier manuellement', max_length=150, null=True, verbose_name='Nom officiel retourné par OBR'),
        ),
    ]
