# Generated by Django 6.0.3 on 2026-04-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_unique_together_and_more'),
    ]

    operations = [
    ]
