# Generated by Django 6.0.3 on 2026-04-29 11:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20260428_2146'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='typeclient',
            name='est_defaut',
            field=models.BooleanField(default=False, verbose_name='Type par défaut'),
        ),
        migrations.AlterField(
            model_name='client',
            name='assujeti_tva',
            field=models.BooleanField(default=False, verbose_name='Assujetti à la TVA'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_verification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nif',
            field=models.CharField(blank=True, help_text="Numéro d'Identification Fiscale", max_length=50, null=True, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom_obr_officiel',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
