# Generated by Django 6.0.6 on 2026-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_typeclient_est_defaut_alter_client_assujeti_tva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='obr_mode_envoye',
            field=models.BooleanField(default=False, editable=False, verbose_name='Mode PRODUCTION'),
        ),
        migrations.AddField(
            model_name='typeclient',
            name='obr_mode_envoye',
            field=models.BooleanField(default=False, editable=False, verbose_name='Mode PRODUCTION'),
        ),
    ]
