# Generated by Django 6.0.6 on 2026-07-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_obr_mode_envoye_typeclient_obr_mode_envoye'),
        ('societe', '0013_alter_societe_obr_base_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('societe', 'nif', 'obr_mode_envoye')},
        ),
        migrations.AlterUniqueTogether(
            name='typeclient',
            unique_together={('societe', 'nom', 'obr_mode_envoye')},
        ),
    ]
