# Generated by Django 5.1.4 on 2026-02-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('societe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valeur (%)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taux', to='societe.societe')),
            ],
            options={
                'verbose_name': 'Taux TVA',
                'verbose_name_plural': 'Taux TVA',
                'ordering': ['valeur'],
                'unique_together': {('societe', 'nom')},
            },
        ),
    ]
