# Generated by Django 6.0.3 on 2026-05-06 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0011_societe_facture_logo_societe_facture_pied_page_and_more'),
        ('taux', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taux',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taux',
            name='societe',
        ),
        migrations.CreateModel(
            name='TauxTVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du taux')),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Exemple : 18.00 pour 18%', max_digits=5, verbose_name='Taux (%)')),
                ('est_defaut', models.BooleanField(default=False, verbose_name='Taux par défaut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taux_tva', to='societe.societe', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Taux TVA',
                'verbose_name_plural': 'Taux TVA',
                'ordering': ['valeur'],
            },
        ),
    ]
