# Generated by Django 6.0.3 on 2026-05-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_alter_produit_options_alter_produit_code_and_more'),
        ('services', '0003_alter_service_taux_tva'),
        ('societe', '0012_societe_obr_mode_production'),
        ('taux', '0002_alter_taux_unique_together_remove_taux_societe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taux',
        ),
        migrations.AlterField(
            model_name='tauxtva',
            name='valeur',
            field=models.DecimalField(decimal_places=2, help_text='Exemple : 18.00 pour 18%, 10.00 pour 10%', max_digits=5, verbose_name='Taux (%)'),
        ),
        migrations.AlterUniqueTogether(
            name='tauxtva',
            unique_together={('societe', 'nom')},
        ),
        migrations.AddConstraint(
            model_name='tauxtva',
            constraint=models.UniqueConstraint(fields=('societe', 'valeur'), name='unique_taux_valeur_par_societe'),
        ),
    ]
