# Generated by Django 6.0.3 on 2026-05-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_alter_produit_taux_tva_alter_produit_unite'),
        ('services', '0003_alter_service_taux_tva'),
        ('taux', '0002_alter_taux_unique_together_remove_taux_societe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taux',
        ),
        migrations.AddConstraint(
            model_name='tauxtva',
            constraint=models.UniqueConstraint(fields=('societe', 'valeur'), name='unique_taux_valeur_par_societe'),
        ),
        migrations.AlterUniqueTogether(
            name='tauxtva',
            unique_together={('societe', 'nom')},
        ),
    ]
