# Generated by Django 6.0.3 on 2026-05-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taux', '0003_delete_taux_tauxtva_unique_taux_valeur_par_societe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tauxtva',
            name='valeur',
            field=models.DecimalField(decimal_places=2, help_text='Exemple : 18.00 pour 18%, 10.00 pour 10%', max_digits=5, verbose_name='Taux (%)'),
        ),
    ]
