# Generated by Django 5.1.7 on 2026-05-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taux', '0004_alter_tauxtva_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tauxtva',
            name='valeur',
            field=models.DecimalField(decimal_places=3, help_text='Exemple : 18.000 pour 18%, 16.667 pour 16.667%, 5.500 pour 5.5%', max_digits=6, verbose_name='Taux (%)'),
        ),
    ]
