# Generated by Django 6.0.6 on 2026-07-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taux', '0005_alter_tauxtva_valeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='tauxtva',
            name='obr_mode_envoye',
            field=models.BooleanField(default=False, editable=False, verbose_name='Mode PRODUCTION'),
        ),
    ]
