# Generated by Django 6.0.6 on 2026-07-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0016_alter_societe_obr_base_url'),
        ('taux', '0010_force_default_rates_production'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tauxtva',
            name='unique_taux_valeur_par_societe',
        ),
        migrations.AlterUniqueTogether(
            name='tauxtva',
            unique_together={('societe', 'nom', 'obr_mode_envoye')},
        ),
        migrations.AddConstraint(
            model_name='tauxtva',
            constraint=models.UniqueConstraint(fields=('societe', 'valeur', 'obr_mode_envoye'), name='unique_taux_valeur_par_societe'),
        ),
    ]
