# Generated by Django 5.1.4 on 2026-02-19 14:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('societe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('postnom', models.CharField(max_length=100, verbose_name='Post-nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('type_poste', models.CharField(choices=[('DIRECTEUR', 'Directeur Général'), ('COMPTABLE', 'Comptable'), ('VENDEUR', 'Vendeur'), ('MAGASINIER', 'Magasinier'), ('ASSISTANT', 'Assistant'), ('AUTRE', 'Autre')], default='VENDEUR', max_length=20, verbose_name='Type de poste')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Photo de profil')),
                ('droit_stock_categorie', models.BooleanField(default=False, verbose_name='Droit : Catégories')),
                ('droit_stock_produit', models.BooleanField(default=False, verbose_name='Droit : Produits')),
                ('droit_stock_fournisseur', models.BooleanField(default=False, verbose_name='Droit : Fournisseurs')),
                ('droit_stock_entree', models.BooleanField(default=False, verbose_name='Droit : Entrées stock')),
                ('droit_stock_sortie', models.BooleanField(default=False, verbose_name='Droit : Sorties stock')),
                ('droit_facture_pnb', models.BooleanField(default=False, verbose_name='Droit : PNB')),
                ('droit_facture_fdnb', models.BooleanField(default=False, verbose_name='Droit : FDNB')),
                ('droit_facture_particulier', models.BooleanField(default=False, verbose_name='Droit : Particuliers')),
                ('droit_devis', models.BooleanField(default=False, verbose_name='Droit : Devis')),
                ('droit_rapports', models.BooleanField(default=True, verbose_name='Droit : Rapports')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='societe.societe', verbose_name='Société')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['nom', 'prenom'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_backup', models.DateTimeField(auto_now_add=True, verbose_name='Date de backup')),
                ('type_backup', models.CharField(choices=[('COMPLET', 'Backup Complet'), ('PARTIEL', 'Backup Partiel')], default='COMPLET', max_length=20, verbose_name='Type')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='backups/', verbose_name='Fichier')),
                ('taille_fichier', models.BigIntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('succes', models.BooleanField(default=True, verbose_name='Succès')),
                ('message', models.TextField(blank=True, verbose_name='Message/Erreur')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-date_backup'],
            },
        ),
        migrations.CreateModel(
            name='CleActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_visible', models.CharField(editable=False, max_length=50, unique=True)),
                ('empreinte_hmac', models.CharField(blank=True, editable=False, max_length=64)),
                ('type_plan', models.CharField(choices=[('ESSAI', 'Essai gratuit (14 jours)'), ('STARTER', 'Starter (6 mois)'), ('BUSINESS', 'Business (12 mois)'), ('ENTERPRISE', 'Enterprise (24 mois)')], default='STARTER', max_length=20, verbose_name='Type de plan')),
                ('duree_mois', models.PositiveSmallIntegerField(default=6, help_text='Calculé automatiquement depuis type_plan. 0 = essai 14 jours.', verbose_name='Durée (mois)')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible — prête à être remise au chef'), ('ACTIVE', 'Active — le chef a activé son accès'), ('EXPIREE', 'Expirée'), ('REVOQUEE', "Révoquée par l'admin")], default='DISPONIBLE', help_text='Mis à jour automatiquement. DISPONIBLE → chef reçoit la clé. ACTIVE → chef a activé.', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valide à partir du')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('active', models.BooleanField(default=True, help_text="L'admin peut désactiver/réactiver manuellement", verbose_name="Activée par l'admin")),
                ('utilisee', models.BooleanField(default=False, help_text='True quand le chef a entré la clé et activé son accès', verbose_name='Utilisée par le chef')),
                ('date_utilisation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'activation")),
                ('cree_par', models.CharField(default='superadmin', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('motif_revocation', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('societe', models.ForeignKey(help_text='La clé est créée spécifiquement pour cette société (nom + NIF).', on_delete=django.db.models.deletion.CASCADE, related_name='cles_activation', to='societe.societe', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Clé d'activation",
                'verbose_name_plural': "Clés d'activation",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AuditCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREEE', 'Clé créée'), ('ACTIVEE', 'Clé activée'), ('REVOQUEE', 'Clé révoquée'), ('ECHEC', 'Tentative échouée'), ('SUSPENDUE', 'Société suspendue'), ('REACTIVEE', 'Société réactivée'), ('PROLONGEE', 'Clé prolongée')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='societe.societe')),
                ('cle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.cleactivation')),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_connexion', models.DateTimeField(auto_now_add=True, verbose_name='Date de connexion')),
                ('date_deconnexion', models.DateTimeField(blank=True, null=True, verbose_name='Date de déconnexion')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de connexion',
                'verbose_name_plural': 'Historiques de connexion',
                'ordering': ['-date_connexion'],
            },
        ),
    ]
