# Generated by Django 6.0.3 on 2026-04-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleactivation',
            name='type_plan',
            field=models.CharField(choices=[('ESSAI', 'Essai gratuit (14 jours)'), ('1MOIS', '1 Mois'), ('STARTER', 'Starter (6 mois)'), ('BUSINESS', 'Business (12 mois)'), ('ENTERPRISE', 'Enterprise (24 mois)')], default='STARTER', max_length=20, verbose_name='Type de plan'),
        ),
    ]
