# Generated by Django 6.0.3 on 2026-05-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_alter_cleactivation_type_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleactivation',
            name='active',
            field=models.BooleanField(default=True, verbose_name="Activée par l'admin"),
        ),
        migrations.AlterField(
            model_name='cleactivation',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible — prête à être remise au chef'), ('ACTIVE', 'Active — le chef a activé son accès'), ('EXPIREE', 'Expirée'), ('REVOQUEE', "Révoquée par l'admin")], default='DISPONIBLE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='cleactivation',
            name='utilisee',
            field=models.BooleanField(default=False, verbose_name='Utilisée par le chef'),
        ),
    ]
