# Generated by Django 6.0.6 on 2026-06-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_alter_cleactivation_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='WIBABI', max_length=100, verbose_name="Nom de l'application")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name="Logo page d'authentification")),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration générale',
                'verbose_name_plural': 'Configuration générale',
            },
        ),
        migrations.AlterField(
            model_name='cleactivation',
            name='active',
            field=models.BooleanField(default=True, help_text="L'admin peut désactiver/réactiver manuellement", verbose_name="Activée par l'admin"),
        ),
        migrations.AlterField(
            model_name='cleactivation',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible — prête à être remise au chef'), ('ACTIVE', 'Active — le chef a activé son accès'), ('EXPIREE', 'Expirée'), ('REVOQUEE', "Révoquée par l'admin")], default='DISPONIBLE', help_text='Mis à jour automatiquement. DISPONIBLE → chef reçoit la clé. ACTIVE → chef a activé.', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='cleactivation',
            name='type_plan',
            field=models.CharField(choices=[('ESSAI', 'Essai gratuit (14 jours)'), ('STARTER', 'Starter (6 mois)'), ('BUSINESS', 'Business (12 mois)'), ('ENTERPRISE', 'Enterprise (24 mois)')], default='STARTER', max_length=20, verbose_name='Type de plan'),
        ),
        migrations.AlterField(
            model_name='cleactivation',
            name='utilisee',
            field=models.BooleanField(default=False, help_text='True quand le chef a entré la clé et activé son accès', verbose_name='Utilisée par le chef'),
        ),
    ]
