# Generated by Django 6.0.6 on 2026-07-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categorie_obr_mode_envoye'),
        ('societe', '0016_alter_societe_obr_base_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorie',
            unique_together={('societe', 'nom', 'obr_mode_envoye')},
        ),
    ]
