# Generated by Django 6.0.6 on 2026-07-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_add_new_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devis',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Proforma', 'verbose_name_plural': 'Proformas'},
        ),
        migrations.AlterField(
            model_name='devis',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='N° Proforma'),
        ),
    ]
