# Generated by Django 6.0.6 on 2026-07-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_alter_devis_options_alter_devis_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='obr_mode_envoye',
            field=models.BooleanField(default=False, editable=False, verbose_name='Mode PRODUCTION'),
        ),
    ]
