# Generated by Django 5.1.4 on 2026-02-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('societe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('adresse', models.CharField(blank=True, max_length=250, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='societe.societe')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
                'unique_together': {('societe', 'nom')},
            },
        ),
    ]
