# Generated by Django 5.1.4 on 2026-02-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(choices=[('ENTREES', 'Entrées / Achats'), ('COUT_STOCK', 'Coût du stock vendu'), ('SORTIES', 'Sorties / Ventes'), ('STOCK_ACTUEL', 'Stock actuel'), ('FACTURATION', 'Ventes / Facturation')], max_length=30, verbose_name='Type de rapport')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports/pdf/', verbose_name='Fichier PDF')),
                ('fichier_excel', models.FileField(blank=True, null=True, upload_to='rapports/excel/', verbose_name='Fichier Excel')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-date_creation'],
            },
        ),
    ]
