# Generated by Django 5.1.4 on 2026-02-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250, verbose_name='Désignation')),
                ('quantite_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qté en stock')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='TVA %')),
                ('prix_vente_tvac', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix TVAC')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qté vendue')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, verbose_name='N° Facture')),
                ('date_facture', models.DateField(verbose_name='Date')),
                ('heure_facture', models.TimeField(verbose_name='Heure')),
                ('type_facture', models.CharField(choices=[('FN', 'FN — Facture Normale'), ('FA', 'FA — Facture Avoir / Note de Crédit')], max_length=5, verbose_name='Type')),
                ('bon_commande', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bon de commande')),
                ('devise', models.CharField(choices=[('BIF', 'BIF'), ('USD', 'USD'), ('EURO', 'EURO')], default='BIF', max_length=5, verbose_name='Devise')),
                ('mode_paiement', models.CharField(choices=[('CAISSE', 'Caisse'), ('BANQUE', 'Banque'), ('CREDIT', 'Crédit'), ('AUTRES', 'Autres')], max_length=10, verbose_name='Mode de paiement')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('statut_obr', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé OBR'), ('ECHEC', 'Échec envoi'), ('ANNULE', 'Annulé OBR')], default='EN_ATTENTE', max_length=20)),
                ('message_obr', models.TextField(blank=True)),
                ('date_envoi_obr', models.DateTimeField(blank=True, null=True)),
                ('signature_obr', models.TextField(blank=True, verbose_name='Signature électronique OBR')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_creation'],
            },
        ),
    ]
