# Generated by Django 5.1.4 on 2026-02-19 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturer', '0001_initial'),
        ('produits', '0001_initial'),
        ('services', '0001_initial'),
        ('societe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='societe.societe', verbose_name='Société'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturer.facture'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produits.produit'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.service'),
        ),
        migrations.AlterUniqueTogether(
            name='facture',
            unique_together={('societe', 'numero')},
        ),
    ]
