# Generated by Django 5.1.4 on 2026-03-02 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturePendingOBR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='EN_ATTENTE', max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_obr', to='facturer.facture')),
            ],
            options={
                'verbose_name': 'Facture en attente OBR',
                'verbose_name_plural': 'Factures en attente OBR',
                'db_table': 'facturer_facturependingobr',
            },
        ),
    ]
