# Generated by Django 5.1.4 on 2026-03-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0003_facturependingobr'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturependingobr',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
