# Generated by Django 5.1.4 on 2026-03-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0004_facturependingobr_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='invoice_identifier',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Identifiant facture OBR'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Facture'),
        ),
    ]
