# Generated by Django 5.1.4 on 2026-03-15 21:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0005_facture_invoice_identifier_alter_facture_numero'),
        ('societe', '0005_societe_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='signature_obr',
            new_name='electronic_signature',
        ),
        migrations.AlterUniqueTogether(
            name='facture',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='facture',
            name='facture_originale',
            field=models.ForeignKey(blank=True, help_text='Référence de la facture concernée (obligatoire pour FA)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avoirs_lies', to='facturer.facture', verbose_name='Facture originale'),
        ),
        migrations.AddField(
            model_name='facture',
            name='motif_avoir',
            field=models.CharField(blank=True, help_text='Erreur, retour marchandise, rabais, remise, ristourne...', max_length=150, verbose_name="Motif de l'avoir"),
        ),
        migrations.AddField(
            model_name='facture',
            name='obr_registered_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date enregistrement OBR'),
        ),
        migrations.AddField(
            model_name='facture',
            name='obr_registered_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° enregistré OBR'),
        ),
        migrations.AddField(
            model_name='facture',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/factures/', verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='facturependingobr',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créée le'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_envoi_obr',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date envoi OBR'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_facture',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='devise',
            field=models.CharField(choices=[('BIF', 'BIF — Franc Burundais'), ('USD', 'USD — Dollar Américain'), ('EUR', 'EUR — Euro')], default='BIF', max_length=5, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='heure_facture',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Heure'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='invoice_identifier',
            field=models.CharField(blank=True, help_text='Format: NIF/system_id/AAAAMMJJHHMMSS/type/numero/annee', max_length=150, null=True, unique=True, verbose_name='Identifiant facture OBR'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='message_obr',
            field=models.TextField(blank=True, verbose_name='Message OBR'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, help_text='Ex: FN/0001/2026 ou FA/0001/2026', max_length=50, verbose_name='N° Facture'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total HT'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total TTC'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total TVA'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('FN', 'FN — Facture Normale'), ('FA', 'FA — Facture Avoir / Note de Crédit')], default='FN', max_length=5, verbose_name='Type'),
        ),
        migrations.AlterUniqueTogether(
            name='facture',
            unique_together={('societe', 'numero', 'type_facture')},
        ),
        migrations.AlterModelTable(
            name='facturependingobr',
            table=None,
        ),
    ]
