# Generated by Django 5.1.4 on 2026-03-22 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_avenue_client_commune_client_cree_par_and_more'),
        ('facturer', '0006_rename_signature_obr_facture_electronic_signature_and_more'),
        ('societe', '0006_societe_nom_complet_gerant_societe_numero_depart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='cree_par',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_envoi_obr',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='electronic_signature',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_originale',
            field=models.ForeignKey(blank=True, help_text='Obligatoire pour les avoirs (FA)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avoirs_lies', to='facturer.facture', verbose_name='Facture originale'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='invoice_identifier',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Identifiant facture OBR'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='message_obr',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(choices=[('CAISSE', 'Caisse'), ('BANQUE', 'Banque'), ('CREDIT', 'Crédit'), ('AUTRES', 'Autres')], default='CAISSE', max_length=10, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='motif_avoir',
            field=models.CharField(blank=True, max_length=150, verbose_name="Motif de l'avoir"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, editable=False, help_text='Format stocké : 00001/2026 (séquence/année)', max_length=50, verbose_name='N° Facture interne'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='obr_registered_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='obr_registered_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/factures/'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut_obr',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé OBR'), ('ECHEC', 'Échec envoi'), ('ANNULE', 'Annulé OBR')], default='EN_ATTENTE', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_tva',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['societe', 'type_facture', 'date_facture'], name='facturer_fa_societe_ecdbce_idx'),
        ),
    ]
