# Generated by Django 6.0.3 on 2026-04-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0007_alter_facture_cree_par_alter_facture_date_creation_and_more'),
        ('societe', '0007_societe_email_societe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facture',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, editable=False, help_text='Format stocké : FN/2/2026 (type/séquence/année)', max_length=50, verbose_name='N° Facture'),
        ),
        migrations.AlterUniqueTogether(
            name='facture',
            unique_together={('societe', 'numero')},
        ),
    ]
