# Generated by Django 6.0.3 on 2026-04-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0008_alter_facture_unique_together_alter_facture_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
