# Generated by Django 6.0.3 on 2026-04-30 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_typeclient_est_defaut_alter_client_assujeti_tva_and_more'),
        ('facturer', '0009_facture_date_annulation'),
        ('societe', '0010_alter_societe_obr_base_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration (nettoyage auto)"),
        ),
        migrations.AddField(
            model_name='facture',
            name='est_abandonnee',
            field=models.BooleanField(default=False, verbose_name='Facture abandonnée'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['societe', 'statut_obr', 'date_creation'], name='facturer_fa_societe_c12e54_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['societe', 'est_abandonnee', 'date_expiration'], name='facturer_fa_societe_d54051_idx'),
        ),
    ]
