# Generated by Django 6.0.3 on 2026-05-06 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0010_facture_date_expiration_facture_est_abandonnee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturependingobr',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='facture',
            name='facturer_fa_societe_c12e54_idx',
        ),
        migrations.RemoveIndex(
            model_name='facture',
            name='facturer_fa_societe_d54051_idx',
        ),
        migrations.RemoveField(
            model_name='lignefacture',
            name='prix_vente_tvac',
        ),
        migrations.RemoveField(
            model_name='lignefacture',
            name='quantite_stock',
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='prix_unitaire_ht',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Prix unitaire HT'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_originale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avoirs_lies', to='facturer.facture', verbose_name='Facture originale'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='motif_avoir',
            field=models.CharField(blank=True, max_length=500, verbose_name="Motif de l'avoir"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='N° Facture'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_ht',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_ttc',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_tva',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='facturependingobr',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='designation',
            field=models.CharField(max_length=500, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='quantite',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Quantité'),
        ),
    ]
