# Generated by Django 6.0.3 on 2026-05-18 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0011_alter_facturependingobr_options_and_more'),
        ('taux', '0003_delete_taux_alter_tauxtva_valeur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturependingobr',
            options={'verbose_name': 'Facture en attente OBR', 'verbose_name_plural': 'Factures en attente OBR'},
        ),
        migrations.RemoveIndex(
            model_name='facture',
            name='facturer_fa_societe_ecdbce_idx',
        ),
        migrations.AddField(
            model_name='facture',
            name='applique_tva',
            field=models.BooleanField(default=True, verbose_name='Appliquer la TVA'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='prix_vente_tvac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix de vente TVAC'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='est_abandonnee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facture',
            name='motif_avoir',
            field=models.CharField(blank=True, max_length=150, verbose_name="Motif de l'avoir"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut_obr',
            field=models.CharField(choices=[('EN_ATTENTE', 'En cours'), ('ENVOYE', 'Envoyé OBR'), ('ECHEC', 'Échec envoi'), ('ANNULE', 'Annulé OBR')], default='EN_ATTENTE', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_tva',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='facturependingobr',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='designation',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='prix_unitaire_ht',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='quantite',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='taux_tva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taux.tauxtva', verbose_name='Taux TVA'),
        ),
    ]
