# Generated by Django 6.0.3 on 2026-05-06 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0011_alter_facturependingobr_options_and_more'),
        ('taux', '0002_alter_taux_unique_together_remove_taux_societe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignefacture',
            name='taux_tva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taux.tauxtva', verbose_name='Taux TVA'),
        ),
        migrations.RemoveField(
            model_name='facture',
            name='date_expiration',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='est_abandonnee',
        ),
    ]
