# Generated by Django 6.0.3 on 2026-05-10 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_typeclient_est_defaut_alter_client_assujeti_tva_and_more'),
        ('facturer', '0012_alter_lignefacture_taux_tva_and_more'),
        ('societe', '0011_societe_facture_logo_societe_facture_pied_page_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterModelOptions(
            name='facturependingobr',
            options={'verbose_name': 'Facture en attente OBR', 'verbose_name_plural': 'Factures en attente OBR'},
        ),
        migrations.RemoveIndex(
            model_name='facture',
            name='facturer_fa_societe_ecdbce_idx',
        ),
        migrations.AddField(
            model_name='facture',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='est_abandonnee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='prix_vente_tvac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='bon_commande',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_facture',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facture',
            name='devise',
            field=models.CharField(choices=[('BIF', 'BIF — Franc Burundais'), ('USD', 'USD — Dollar Américain'), ('EUR', 'EUR — Euro')], default='BIF', max_length=5),
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_originale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avoirs_lies', to='facturer.facture'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='heure_facture',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facture',
            name='invoice_identifier',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(choices=[('CAISSE', 'Caisse'), ('BANQUE', 'Banque'), ('CREDIT', 'Crédit'), ('AUTRES', 'Autres')], default='CAISSE', max_length=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='motif_avoir',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='facture',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='societe.societe'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('FN', 'FN — Facture Normale'), ('FA', 'FA — Facture Avoir / Note de Crédit')], default='FN', max_length=5),
        ),
        migrations.AlterField(
            model_name='facturependingobr',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='designation',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='prix_unitaire_ht',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='quantite',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.RemoveField(
            model_name='facture',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='electronic_signature',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='obr_registered_date',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='obr_registered_number',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='qr_code_image',
        ),
    ]
