# Generated by Django 6.0.3 on 2026-05-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0013_alter_facture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignefacture',
            name='prix_vente_tvac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix de vente TVAC'),
        ),
    ]
