# Generated by Django 6.0.3 on 2026-05-10 19:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_typeclient_est_defaut_alter_client_assujeti_tva_and_more'),
        ('facturer', '0014_alter_lignefacture_prix_vente_tvac'),
        ('societe', '0011_societe_facture_logo_societe_facture_pied_page_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AddField(
            model_name='facture',
            name='cree_par',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par'),
        ),
        migrations.AddField(
            model_name='facture',
            name='electronic_signature',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='facture',
            name='obr_registered_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='obr_registered_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/factures/'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='bon_commande',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bon de commande'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration (nettoyage auto)"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_facture',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='devise',
            field=models.CharField(choices=[('BIF', 'BIF — Franc Burundais'), ('USD', 'USD — Dollar Américain'), ('EUR', 'EUR — Euro')], default='BIF', max_length=5, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='est_abandonnee',
            field=models.BooleanField(default=False, verbose_name='Facture abandonnée'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_originale',
            field=models.ForeignKey(blank=True, help_text='Obligatoire pour les avoirs (FA)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avoirs_lies', to='facturer.facture', verbose_name='Facture originale'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='heure_facture',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Heure'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='invoice_identifier',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Identifiant facture OBR'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(choices=[('CAISSE', 'Caisse'), ('BANQUE', 'Banque'), ('CREDIT', 'Crédit'), ('AUTRES', 'Autres')], default='CAISSE', max_length=10, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='motif_avoir',
            field=models.CharField(blank=True, max_length=150, verbose_name="Motif de l'avoir"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, editable=False, help_text='Format stocké : FN/2/2026 (type/séquence/année)', max_length=50, verbose_name='N° Facture'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='societe.societe', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_tva',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('FN', 'FN — Facture Normale'), ('FA', 'FA — Facture Avoir / Note de Crédit')], default='FN', max_length=5, verbose_name='Type'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['societe', 'type_facture', 'date_facture'], name='facturer_fa_societe_ecdbce_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['societe', 'statut_obr', 'date_creation'], name='facturer_fa_societe_c12e54_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['societe', 'est_abandonnee', 'date_expiration'], name='facturer_fa_societe_d54051_idx'),
        ),
    ]
