# Generated by Django 6.0.3 on 2026-05-10 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0015_alter_facture_options_facture_cree_par_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='facture',
            name='facturer_fa_societe_ecdbce_idx',
        ),
        migrations.RemoveIndex(
            model_name='facture',
            name='facturer_fa_societe_c12e54_idx',
        ),
        migrations.RemoveIndex(
            model_name='facture',
            name='facturer_fa_societe_d54051_idx',
        ),
        migrations.AddField(
            model_name='facture',
            name='applique_tva',
            field=models.BooleanField(default=True, verbose_name='Appliquer la TVA'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='est_abandonnee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_originale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avoirs_lies', to='facturer.facture', verbose_name='Facture originale'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='N° Facture'),
        ),
    ]
