# Generated by Django 6.0.3 on 2026-05-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0016_remove_facture_facturer_fa_societe_ecdbce_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='statut_obr',
            field=models.CharField(choices=[('EN_ATTENTE', 'En cours'), ('ENVOYE', 'Envoyé OBR'), ('ECHEC', 'Échec envoi'), ('ANNULE', 'Annulé OBR')], default='EN_ATTENTE', editable=False, max_length=20),
        ),
    ]
