# Generated by Django 6.0.3 on 2026-05-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0017_alter_facture_statut_obr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='total_ht',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_ttc',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_tva',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='prix_vente_tvac',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Prix de vente TVAC'),
        ),
    ]
