# Generated by Django 6.0.6 on 2026-06-13 18:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_typeclient_est_defaut_alter_client_assujeti_tva_and_more'),
        ('facturer', '0018_alter_facture_total_ht_alter_facture_total_ttc_and_more'),
        ('produits', '0009_alter_produit_options_alter_produit_code_and_more'),
        ('services', '0003_alter_service_taux_tva'),
        ('societe', '0013_alter_societe_forme'),
        ('taux', '0005_alter_tauxtva_valeur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, editable=False, max_length=50, verbose_name='N° Devis')),
                ('date_devis', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('date_validite', models.DateField(verbose_name="Valable jusqu'au")),
                ('devise', models.CharField(choices=[('BIF', 'BIF — Franc Burundais'), ('USD', 'USD — Dollar Américain'), ('EUR', 'EUR — Euro')], default='BIF', max_length=5, verbose_name='Devise')),
                ('applique_tva', models.BooleanField(default=True, verbose_name='Appliquer la TVA')),
                ('total_ht', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=14)),
                ('total_tva', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=14)),
                ('total_ttc', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=14)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('EXPIRE', 'Expiré'), ('TRANSFORME', 'Transformé en facture')], default='BROUILLON', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Conditions')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='clients.client', verbose_name='Client')),
                ('cree_par', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='societe.societe', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_creation'],
                'unique_together': {('societe', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250)),
                ('quantite', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('prix_vente_tvac', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Prix de vente TVAC')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='facturer.devis')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.service')),
                ('taux_tva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taux.tauxtva', verbose_name='Taux TVA')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
