# Generated by Django 6.0.6 on 2026-07-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0019_facture_obr_mode_envoye'),
        ('societe', '0013_alter_societe_obr_base_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facture',
            unique_together={('societe', 'numero', 'obr_mode_envoye')},
        ),
    ]
