# Generated by Django 6.0.6 on 2026-07-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturer', '0020_remove_devis_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='obr_mode_envoye',
            field=models.BooleanField(default=False, editable=False, verbose_name='Envoyé en mode PRODUCTION'),
        ),
    ]
