# Generated by Django 5.1.4 on 2026-02-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la société')),
                ('nif', models.CharField(help_text="Doit être exact. Le chef ne pourra s'inscrire qu'avec ce NIF.", max_length=50, unique=True, verbose_name='NIF')),
                ('registre', models.CharField(blank=True, default='', max_length=100, verbose_name='Registre de commerce')),
                ('boite_postal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Boîte postale')),
                ('telephone', models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone')),
                ('province', models.CharField(blank=True, default='', max_length=100, verbose_name='Province')),
                ('commune', models.CharField(blank=True, default='', max_length=100, verbose_name='Commune / Commerce')),
                ('quartier', models.CharField(blank=True, default='', max_length=100, verbose_name='Quartier')),
                ('avenue', models.CharField(blank=True, default='', max_length=150, verbose_name='Avenue')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro')),
                ('centre_fiscale', models.CharField(blank=True, choices=[('DGC', 'DGC — Direction Générale des Contributions'), ('DMC', 'DMC — Direction des Moyennes Contributions'), ('DPMC', 'DPMC — Direction des Petites et Moyennes Contributions'), ('PRIVEE', 'Société Privée'), ('SU', 'SU — Service des Unités')], default='', max_length=10, verbose_name='Centre fiscal')),
                ('assujeti_tva', models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, verbose_name='Assujetti TVA')),
                ('assujeti_tc', models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, verbose_name='Assujetti à la TC')),
                ('obr_username', models.CharField(blank=True, default='', help_text="Identifiant fourni par l'OBR pour l'accès à l'API eBMS.", max_length=100, verbose_name="Nom d'utilisateur OBR")),
                ('obr_password', models.CharField(blank=True, default='', help_text="Mot de passe fourni par l'OBR pour l'API eBMS.", max_length=100, verbose_name='Mot de passe OBR')),
                ('obr_system_id', models.CharField(blank=True, default='', help_text="Ex: ws440077324400027 — fourni par l'OBR avec le mot de passe.", max_length=100, verbose_name='Identifiant système OBR')),
                ('obr_actif', models.BooleanField(default=False, help_text="Activer l'envoi automatique des données à l'OBR.", verbose_name='Intégration OBR activée')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Société',
                'verbose_name_plural': 'Sociétés',
                'ordering': ['nom'],
            },
        ),
    ]
