# Generated by Django 5.1.4 on 2026-02-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='forme',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Forme juridique'),
        ),
        migrations.AddField(
            model_name='societe',
            name='secteur',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name="Secteur d'activité"),
        ),
    ]
