# Generated by Django 5.1.4 on 2026-02-25 08:30

from django.db import migrations, models  # ajoute models ici

class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0002_societe_forme_societe_secteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='logo',
            field=models.ImageField(upload_to='logos/', null=True, blank=True),
        ),
    ]