# Generated by Django 5.1.4 on 2026-02-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0003_add_logo_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societe',
            name='logo',
        ),
    ]
