# Generated by Django 5.1.4 on 2026-02-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0004_remove_societe_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo de la société'),
        ),
    ]
