# Generated by Django 5.1.4 on 2026-03-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0005_societe_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='nom_complet_gerant',
            field=models.CharField(blank=True, help_text='Nom complet du gérant de la société.', max_length=200, verbose_name='Nom complet du gérant'),
        ),
        migrations.AddField(
            model_name='societe',
            name='numero_depart',
            field=models.PositiveIntegerField(default=0, help_text='Numéro à partir duquel la séquence des factures commence (admin peut définir).', verbose_name='Numéro de départ facture'),
        ),
    ]
