# Generated by Django 5.1.4 on 2026-03-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0006_societe_nom_complet_gerant_societe_numero_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='email_societe',
            field=models.EmailField(blank=True, help_text='Adresse email officielle de la société (réservé superadmin).', max_length=254, verbose_name='Email de la société'),
        ),
    ]
