# Generated by Django 6.0.3 on 2026-04-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0007_societe_email_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='assujeti_pfl',
            field=models.BooleanField(default=False, verbose_name='Assujetti au Prélèvement Forfaitaire Libératoire (PFL)'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='assujeti_tc',
            field=models.BooleanField(default=False, verbose_name='Assujetti à la Taxe de Consommation (TC)'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='assujeti_tva',
            field=models.BooleanField(default=False, verbose_name='Assujetti à la TVA'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='centre_fiscale',
            field=models.CharField(blank=True, choices=[('DGC', 'DGC — Direction Générale des Contributions'), ('DMC', 'DMC — Direction des Moyennes Contributions'), ('DPMC', 'DPMC — Direction des Petites et Moyennes Contributions'), ('PRIVEE', 'Société Privée'), ('SU', 'SU — Service des Unités')], help_text='DGC, DMC, DPMC, PRIVEE, SU', max_length=10, verbose_name='Centre fiscal'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='commune',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='email_societe',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de la société'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='forme',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Forme juridique'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='numero_depart',
            field=models.PositiveIntegerField(default=1, help_text='Numéro à partir duquel la séquence des factures commence.', verbose_name='Numéro de départ facture'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='secteur',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name="Secteur d'activité"),
        ),
    ]
