# Generated by Django 6.0.3 on 2026-04-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0008_societe_assujeti_pfl_alter_societe_assujeti_tc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='obr_base_url',
            field=models.URLField(blank=True, help_text='Laisser vide pour utiliser par défaut : https://ebms.obr.gov.bi:9443/ebms_api', max_length=255, null=True, verbose_name='URL API OBR (personnalisée)'),
        ),
    ]
