# Generated by Django 6.0.3 on 2026-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0009_societe_obr_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='obr_base_url',
            field=models.URLField(blank=True, default='https://ebms.obr.gov.bi:9443/ebms_api', help_text='Laisser vide pour utiliser par défaut : https://ebms.obr.gov.bi:9443/ebms_api', max_length=255, null=True, verbose_name='URL API OBR (personnalisée)'),
        ),
    ]
