# Generated by Django 6.0.3 on 2026-05-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0010_alter_societe_obr_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='facture_logo',
            field=models.ImageField(blank=True, help_text='Image qui apparaîtra en haut des factures (taille recommandée : 800x250 px)', null=True, upload_to='factures/logos/', verbose_name="Logo / Photo d'en-tête de facture"),
        ),
        migrations.AddField(
            model_name='societe',
            name='facture_pied_page',
            field=models.TextField(blank=True, default='', help_text='Texte qui apparaîtra en bas de chaque facture (mentions légales, RIB, etc.)', verbose_name='Pied de page de facture'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='centre_fiscale',
            field=models.CharField(blank=True, choices=[('DGC', 'DGC — Direction Générale des Contributions'), ('DMC', 'DMC — Direction des Moyennes Contributions'), ('DPMC', 'DPMC — Direction des Petites et Moyennes Contributions'), ('PRIVEE', 'Société Privée'), ('SU', 'SU — Service des Unités')], max_length=10, verbose_name='Centre fiscal'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='nom_complet_gerant',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom complet du gérant'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='numero_depart',
            field=models.PositiveIntegerField(default=1, verbose_name='Numéro de départ facture'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='obr_actif',
            field=models.BooleanField(default=False, verbose_name='Intégration OBR activée'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='obr_base_url',
            field=models.URLField(blank=True, default='https://ebms.obr.gov.bi:9443/ebms_api', help_text='Laisser vide pour utiliser par défaut', max_length=255, null=True, verbose_name='URL API OBR (personnalisée)'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='obr_password',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Mot de passe OBR'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='obr_system_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Identifiant système OBR'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='obr_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name="Nom d'utilisateur OBR"),
        ),
    ]
