# Generated by Django 6.0.3 on 2026-05-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0011_societe_facture_logo_societe_facture_pied_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='obr_mode_production',
            field=models.BooleanField(default=False, help_text='Décochez pour Test (9443) | Cochez pour Production (8443)', verbose_name='Mode PRODUCTION'),
        ),
    ]
