# Generated by Django 5.1.7 on 2026-05-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0012_societe_obr_mode_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='forme',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Forme juridique'),
        ),
    ]
