# Generated by Django 6.0.6 on 2026-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0012_societe_obr_mode_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='obr_base_url',
            field=models.URLField(blank=True, help_text='Laisser vide pour utiliser le port par défaut selon le mode (TEST=9443, PRODUCTION=8443)', max_length=255, null=True, verbose_name='URL API OBR (personnalisée)'),
        ),
    ]
