# Generated by Django 6.0.6 on 2026-06-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0013_alter_societe_forme'),
    ]

    operations = [
    ]
