# Generated by Django 5.1.4 on 2026-02-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('societe', '0001_initial'),
        ('taux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('unite', models.CharField(max_length=20, verbose_name='Unité')),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('devise', models.CharField(choices=[('BIF', 'BIF'), ('USD', 'USD'), ('EURO', 'EURO')], default='BIF', max_length=10, verbose_name='Devise')),
                ('origine', models.CharField(choices=[('LOCAL', 'Produit Local'), ('IMPORTE', 'Produit Importé')], max_length=10, verbose_name='Origine')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('BROUILLON', 'Brouillon')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('reference_dmc', models.CharField(blank=True, default='', help_text='Référence de la déclaration de mise en consommation. Ex: 2025BIPORC9', max_length=100, verbose_name='Référence DMC')),
                ('rubrique_tarifaire', models.CharField(blank=True, default='', help_text='Code dans le tarif douanier. Ex: 15119090000', max_length=50, verbose_name='Rubrique tarifaire')),
                ('nombre_par_paquet', models.FloatField(blank=True, help_text='Nombre de pièces par paquet. Ex: 300', null=True, verbose_name='Nombre par paquet')),
                ('description_paquet', models.CharField(blank=True, default='', help_text='Type de conditionnement. Ex: carton, sacs, boîte', max_length=50, verbose_name='Description paquet')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='categories.categorie', verbose_name='Catégorie')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='societe.societe')),
                ('taux_tva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='taux.taux', verbose_name='Taux TVA')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['designation'],
                'unique_together': {('societe', 'code')},
            },
        ),
    ]
