# Generated by Django 5.1.4 on 2026-03-15 19:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('produits', '0001_initial'),
        ('societe', '0005_societe_logo'),
        ('taux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code',
            field=models.CharField(help_text='Code interne unique à la société (ex: PROD-001)', max_length=50, verbose_name='Code produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description_paquet',
            field=models.CharField(blank=True, default='', help_text='Ex: carton de 12, sachet de 500g, boîte', max_length=150, verbose_name='Description conditionnement'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='designation',
            field=models.CharField(help_text='Nom complet du produit', max_length=200, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='devise',
            field=models.CharField(choices=[('BIF', 'BIF — Franc Burundais'), ('USD', 'USD — Dollar Américain'), ('EUR', 'EUR — Euro')], default='BIF', max_length=10, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nombre_par_paquet',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de pièces/unité par conditionnement', null=True, verbose_name='Nombre par paquet'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, help_text='Prix de vente HTVA', max_digits=12, verbose_name='Prix de vente unitaire'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='reference_dmc',
            field=models.CharField(blank=True, default='', help_text='Référence de la déclaration de mise en consommation (OBR)', max_length=100, verbose_name='Référence DMC'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='rubrique_tarifaire',
            field=models.CharField(blank=True, default='', help_text='Code du tarif douanier (ex: 15119090000)', max_length=50, verbose_name='Rubrique tarifaire'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='societe.societe', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite',
            field=models.CharField(help_text='Ex: kg, litre, pièce, carton', max_length=50, verbose_name='Unité de mesure'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['societe', 'code'], name='produits_pr_societe_c64d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['societe', 'origine'], name='produits_pr_societe_ff22c1_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['reference_dmc'], name='produits_pr_referen_d062f4_idx'),
        ),
    ]
