# Generated by Django 5.1.4 on 2026-03-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_alter_produit_code_alter_produit_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['code', 'designation'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, help_text='Prix de vente hors taxes (HTVA)', max_digits=12, verbose_name='Prix de vente unitaire HT'),
        ),
    ]
