# Generated by Django 5.1.4 on 2026-03-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_alter_produit_options_alter_produit_prix_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='origine',
            field=models.CharField(choices=[('LOCAL', 'Produit Local'), ('IMPORTE', 'Produit Importé')], default='LOCAL', max_length=10, verbose_name='Origine'),
        ),
    ]
