# Generated by Django 6.0.3 on 2026-05-06 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_alter_produit_origine'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='produit',
            name='produits_pr_societe_c64d9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='produit',
            name='produits_pr_societe_ff22c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='produit',
            name='produits_pr_referen_d062f4_idx',
        ),
        migrations.AlterField(
            model_name='produit',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Code produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description_paquet',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='produit',
            name='designation',
            field=models.CharField(max_length=200, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='devise',
            field=models.CharField(choices=[('BIF', 'BIF — Franc Burundais'), ('USD', 'USD — Dollar Américain'), ('EUR', 'EUR — Euro')], default='BIF', max_length=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nombre_par_paquet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='origine',
            field=models.CharField(choices=[('LOCAL', 'Produit Local'), ('IMPORTE', 'Produit Importé')], default='LOCAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Prix de vente unitaire HT'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='reference_dmc',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='rubrique_tarifaire',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='produit',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('BROUILLON', 'Brouillon')], default='ACTIF', max_length=20),
        ),
    ]
