# Generated by Django 6.0.3 on 2026-05-18 17:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_alter_produit_origine'),
        ('taux', '0002_alter_taux_unique_together_remove_taux_societe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['code'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterField(
            model_name='produit',
            name='code',
            field=models.CharField(help_text='Code interne unique à la société', max_length=50, verbose_name='Code produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description_paquet',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Description conditionnement'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='designation',
            field=models.CharField(max_length=200, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='devise',
            field=models.CharField(choices=[('BIF', 'BIF — Franc Burundais'), ('USD', 'USD — Dollar Américain'), ('EUR', 'EUR — Euro')], default='BIF', max_length=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nombre_par_paquet',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre par paquet'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='origine',
            field=models.CharField(choices=[('LOCAL', 'Produit Local'), ('IMPORTE', 'Produit Importé')], default='LOCAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Prix de vente unitaire HT'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='reference_dmc',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Référence DMC'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='rubrique_tarifaire',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Rubrique tarifaire'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('BROUILLON', 'Brouillon')], default='ACTIF', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='taux_tva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='taux.tauxtva', verbose_name='Taux TVA'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite',
            field=models.CharField(max_length=50, verbose_name='Unité de mesure'),
        ),
    ]
