# Generated by Django 6.0.3 on 2026-05-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_alter_produit_origine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code',
            field=models.CharField(help_text='Code interne unique', max_length=50, verbose_name='Code produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description_paquet',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Description conditionnement'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='designation',
            field=models.CharField(max_length=200, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nombre_par_paquet',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre par paquet'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de vente unitaire HT'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='reference_dmc',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Référence DMC'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='rubrique_tarifaire',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Rubrique tarifaire'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite',
            field=models.CharField(max_length=50, verbose_name='Unité de mesure'),
        ),
    ]
