# Generated by Django 6.0.3 on 2026-05-06 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_alter_produit_options_alter_produit_code_and_more'),
        ('taux', '0005_alter_tauxtva_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='taux_tva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='taux.tauxtva', verbose_name='Taux TVA'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite',
            field=models.CharField(max_length=50, verbose_name='Unité de mesure'),
        ),
    ]
