# Generated by Django 6.0.3 on 2026-05-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_alter_produit_taux_tva_alter_produit_unite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['code'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterField(
            model_name='produit',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code produit'),
        ),
    ]
