# Generated by Django 6.0.3 on 2026-05-08 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('produits', '0007_alter_produit_options_alter_produit_code'),
        ('societe', '0011_societe_facture_logo_societe_facture_pied_page_and_more'),
        ('taux', '0003_delete_taux_tauxtva_unique_taux_valeur_par_societe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code',
            field=models.CharField(help_text='Code interne unique à la société', max_length=50, verbose_name='Code produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description_paquet',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Description conditionnement'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nombre_par_paquet',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre par paquet'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='reference_dmc',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Référence DMC'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='rubrique_tarifaire',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Rubrique tarifaire'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='taux_tva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='taux.tauxtva', verbose_name='Taux TVA'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['societe', 'code'], name='produits_pr_societe_c64d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['societe', 'origine'], name='produits_pr_societe_ff22c1_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['reference_dmc'], name='produits_pr_referen_d062f4_idx'),
        ),
    ]
