# Generated by Django 6.0.6 on 2026-06-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0009_alter_produit_options_alter_produit_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_vente',
            field=models.DecimalField(decimal_places=3, help_text='Prix de vente hors taxes (HTVA)', max_digits=14, verbose_name='Prix de vente unitaire HT'),
        ),
    ]
