# Generated by Django 6.0.6 on 2026-07-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0010_alter_produit_prix_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='obr_mode_envoye',
            field=models.BooleanField(default=False, editable=False, verbose_name='Mode PRODUCTION'),
        ),
    ]
